### ISSUE TITLE
vim9script offers significant improvements over the legacy script

### ISSUE THREAD

**Issue by Konfekt** [girishji/vimbits#1]
That's true, though I though these mainly apply to them as scripting languages rather than for command-line. 
The one such listed advantage applying to the latter seems to be Unicode handling.

Is there any difference between `:vim9script :%substitute` and `%substitute`, say in speed?

**Comment by girishji** [comment]
Not in this case. `:s` is handled by native C code, not vim script. You can verify like this:
 `:let x = reltime() | %s/foo/bar/ | echom x->reltime()->reltimestr()` 
vs 
`:vim9 g:x = reltime() | %s/foo/bar/ | echom g:x->reltime()->reltimestr()`. 
On a 20M file they both take 1.04 seconds, when I measured.

[This link](https://github.com/lacygoill/wiki/blob/main/vim/vim9.md) says vim9 is 10-100x faster.

**Comment by Konfekt** [comment]
Thank you. So while the Vimscript syntax takes some time to getting used to, for single shot commands there's no speed benefit. So on the command-line, Vim9script's benefits are rather more digestible syntax and Unicode handling.

**Comment by girishji** [comment]
"Vim9script's benefits are rather more digestible syntax and Unicode handling"
That is absolutely correct.
On a different note, vim9script does not complete global variable or functions (like `let g:<tab>` or `call g:<tab>` in wildmenu legacy script). This should be fixed in Vim.
